# Run Python and Shell linters via pre-commit (used locally and in CI)
default_language_version:
  python: python3.11

exclude: |
  (?x)^(
    data/|
    models/|
    \.venv/|
    venv/|
    env/|
    \.git/|
    \.ruff_cache/|
    \.mypy_cache/
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-shfmt
    rev: v3.7.0
    hooks:
      - id: shfmt
        args: [-d, -i, "2", -ci, -s]

  - repo: https://github.com/pre-commit/mirrors-shellcheck
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: [-x]
