[tool.ruff]
line-length = 180
exclude = ["data", "models"]
src = ["src"]

[tool.ruff.lint]
# Basic errors/warnings + import sorting (safe, broadly applicable)
select = ["E", "F", "I"]
ignore = []

[tool.ruff.lint.isort]
# Treat local modules as first-party
known-first-party = [
  "app",
  "crawler",
  "indexing",
  "inference",
  "processing",
  "training",
  "utils",
]

[tool.ruff.lint.per-file-ignores]
"src/app/streamlit_app.py" = ["E402"]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
